# https://taskfile.dev

version: '3'

vars:

tasks:
  build:
    desc: Build all
    cmds:
      - go build -o bin/xprog ./cmd/xprog

  test:unit:
    desc: Run the unit tests on the host
    cmds:
      - go test -count=1 -short -coverprofile=coverage.out ./... -v

  test:all:vm:clean:
    desc: Run all the tests on a VM from a clean snapshot
    cmds:
      - vagrant snapshot restore pristine
      - task: test:all:vm:dirty

  test:all:vm:dirty:
    desc: Run all the tests on a VM on the current snapshot (thus dirty) (faster but inaccurate and flaky)
    cmds:
      - GOOS=linux go test -count=1 -coverprofile=coverage.out -v -exec="$PWD/bin/xprog ssh --cfg $PWD/ssh_config --" ./...

  browser:
    desc: "Show code coverage in browser (usage: task test:all browser)"
    cmds:
      - go tool cover -html=coverage.out

  clean:
    desc: Remove the build artifacts
    cmds:
      - rm -rf bin

  prepare-vm:
    cmds:
    - vagrant destroy --force
    - vagrant up
    # Take snapshot, name `pristine`
    - vagrant snapshot save pristine
    # Generate a SSH configuration file
    - vagrant ssh-config > ssh_config
    - vagrant halt
