# https://taskfile.dev

version: '3'

vars:

tasks:
  build:
    desc: Build all
    cmds:
      - go build -o bin/xprog .

  test:unit:
    desc: Run the unit tests
    cmds:
      - go test -count=1 -short -cover ./...

  test:vm:clean:
    desc: Run the VM-based tests from a clean snapshot
    cmds:
      - vagrant snapshot restore pristine
      - task: test:vm:dirty
    env:
      GOOS: linux

  test:vm:dirty:
    desc: Run the VM-based tests on the current filesystem (faster but inaccurate)
    cmds:
      - go test -count=1 -coverprofile=coverage.out -v -run 'Test.*VM$' -exec="bin/xprog -v ssh --cfg $PWD/ssh_config.vagrant --" ./...
    env:
      GOOS: linux

  test:all:
    desc: Run all the tests (get all coverage)
    cmds:
      - go test -count=1 -coverprofile=coverage.out ./...

  browser:
    desc: "Show code coverage in browser (usage: task test:all browser)"
    cmds:
      - go tool cover -html=coverage.out

  clean:
    desc: Remove the build artifacts
    cmds:
      - rm -rf bin

  prepare-vm:
    cmds:
    - vagrant destroy --force
    - vagrant up
    # Take snapshot, name `pristine`
    - vagrant snapshot save pristine
    # Generate a SSH configuration file
    - vagrant ssh-config > ssh_config.vagrant
    - vagrant halt
